[package]
name = "codedsvk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
xmltree = "0.10.3"

[dependencies]
libc = "0.2.101"